### ISSUE TITLE
Syphon freezes sketch

### ISSUE THREAD

**Issue by ghost** [Visor-Live/visor-builds#5]
I'm getting a repeating error: I can't enable Syphon Output in settings without freezing the sketch. The default sketch will run fine at first, but as soon as Syphon Output is toggled, it freezes and can't be executed again. Also, no Syphon Output is registered from other applications (tested with Simple Client).

The console reads:

java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class jsyphon.JSyphonServer
at processing.opengl.PSurfaceJOGL$2.run(PSurfaceJOGL.java:412)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class jsyphon.JSyphonServer
at codeanticode.syphon.SyphonServer.sendImage(codeanticode/syphon/SyphonServer)
at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:455)
at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:316)
at uri_3a_classloader_3a_.server.lib.visor.managers.syphon_manager_dot_class.invokeOther5:send_image(uri_3a_classloader_3a_/server/lib/visor/managers/uri:classloader:/server/lib/visor/managers/syphon_manager.class:15)
at uri_3a_classloader_3a_.server.lib.visor.managers.syphon_manager_dot_class.after_render(uri:classloader:/server/lib/visor/managers/syphon_manager.class:15)
at uri_3a_classloader_3a_.server.lib.visor.sketch_dot_class.invokeOther5:after_render(uri_3a_classloader_3a_/server/lib/visor/uri:classloader:/server/lib/visor/sketch.class:73)
at uri_3a_classloader_3a_.server.lib.visor.sketch_dot_class.draw(uri:classloader:/server/lib/visor/sketch.class:73)
at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1789)
at org.jruby.RubyArray$INVOKER$i$0$0$each.call(org/jruby/RubyArray$INVOKER$i$0$0$each.gen)
at uri_3a_classloader_3a_.server.lib.visor.sketch_dot_class.invokeOther48:each(uri_3a_classloader_3a_/server/lib/visor/uri:classloader:/server/lib/visor/sketch.class:73)
at uri_3a_classloader_3a_.server.lib.visor.sketch_dot_class.draw(uri:classloader:/server/lib/visor/sketch.class:73)
at uri_3a_classloader_3a_.server.lib.visor.sketch_dot_class.RUBY$method$draw$0$__VARARGS__(uri_3a_classloader_3a_/server/lib/visor/uri:classloader:/server/lib/visor/sketch.class)
at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invokeRuby(org/jruby/javasupport/proxy/JavaProxyConstructor.java:255)
at org.jruby.javasupport.proxy.JavaProxyConstructor$MethodInvocationHandler.invoke(org/jruby/javasupport/proxy/JavaProxyConstructor.java:238)
at org.jruby.proxy.processing.core.PApplet$Proxy2.draw(org/jruby/proxy/processing/core/PApplet$Proxy2)
at processing.core.PApplet.handleDraw(processing/core/PApplet.java:2429)
at processing.opengl.PSurfaceJOGL$DrawListener.display(processing/opengl/PSurfaceJOGL.java:866)
at jogamp.opengl.GLDrawableHelper.displayImpl(jogamp/opengl/GLDrawableHelper.java:692)
at jogamp.opengl.GLDrawableHelper.display(jogamp/opengl/GLDrawableHelper.java:674)
at jogamp.opengl.GLAutoDrawableBase$2.run(jogamp/opengl/GLAutoDrawableBase.java:443)
at jogamp.opengl.GLDrawableHelper.invokeGLImpl(jogamp/opengl/GLDrawableHelper.java:1293)
at jogamp.opengl.GLDrawableHelper.invokeGL(jogamp/opengl/GLDrawableHelper.java:1147)
at com.jogamp.newt.opengl.GLWindow.display(com/jogamp/newt/opengl/GLWindow.java:759)
at com.jogamp.opengl.util.AWTAnimatorImpl.display(com/jogamp/opengl/util/AWTAnimatorImpl.java:81)
at com.jogamp.opengl.util.AnimatorBase.display(com/jogamp/opengl/util/AnimatorBase.java:452)
at com.jogamp.opengl.util.FPSAnimator$MainTask.run(com/jogamp/opengl/util/FPSAnimator.java:178)
at java.util.TimerThread.mainLoop(java/util/Timer.java:555)
at java.util.TimerThread.run(java/util/Timer.java:505)

**Comment by EmperorJack** [comment]
Hi @vjsveskenielsen, thank you for reporting this issue. This should be resolved in the upcoming version of Visor, so you'll have to hold out until then. Cheers

**Comment by EmperorJack** [comment]
Hi @vjsveskenielsen, I've just released Visor version 0.5.0 which should now resolve this issue. Can you let me know if it works for you? Thanks!

**Comment by ghost** [comment]
@EmperorJack yes it seems to be fixed!
